Update Packages-AutoBuild.yml

diff --git a/.github/workflows/Packages-AutoBuild.yml b/.github/workflows/Packages-AutoBuild.yml
--- a/.github/workflows/Packages-AutoBuild.yml
+++ b/.github/workflows/Packages-AutoBuild.yml
@@ -249,7 +249,16 @@ jobs:
               comp
             else
               REPO_TOKEN="${{ env.REPO_TOKEN }}"
-              gitdate=$(curl -H "Authorization: token $REPO_TOKEN" -s "https://api.github.com/repos/kiddin9/kwrt-packages/commits?path=$ipk&per_page=1" | jq -r '.[0].commit.committer.date') || (REPO_TOKEN="${{ secrets.TOKEN_KIDDIN9 }}" && gitdate=$(curl -H "Authorization: token $REPO_TOKEN" -s "https://api.github.com/repos/kiddin9/kwrt-packages/commits?path=$ipk&per_page=1" | jq -r '.[0].commit.committer.date')) || (REPO_TOKEN="${{ secrets.tempgithubk }}" && gitdate=$(curl -H "Authorization: token $REPO_TOKEN" -s "https://api.github.com/repos/kiddin9/kwrt-packages/commits?path=$ipk&per_page=1" | jq -r '.[0].commit.committer.date'))
+              for token in "$REPO_TOKEN" "${{ secrets.TOKEN_KIDDIN9 }}"; do
+                if [ -n "$token" ] && gitdate=$(curl -H "Authorization: token $token" -s "https://api.github.com/repos/kiddin9/kwrt-packages/commits?path=$ipk&per_page=1" | jq -r '.[0].commit.committer.date') && [ "$gitdate" != "null" ]; then
+                  success=true
+                  break
+                fi
+                if [ "$success" = false ]; then
+                  echo "Failed to get commit date with any token"
+                  exit 1
+                fi
+              done
               if [[ "$gitdate" && "$gitdate" != null ]]; then
                 gitdate="$(date -d "$gitdate" +%s)"
                 now="$(date -d "$(date)" +%s)"
